  version: '3'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: >
        sh -c "python manage.py wait_for_db --settings=ukhur.settings.docker &&
                    python manage.py migrate --settings=ukhur.settings.docker &&
                    python manage.py runserver 0.0.0.0:8000 --settings=ukhur.settings.docker"
      volumes:
        - .:/ukhur
      ports:
        - "8000:8000"
      depends_on:
        - db