# Generated by Django 3.0.7 on 2020-06-11 00:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_occurrences_count', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('text', models.TextField(blank=True, null=True)),
                ('word_occurrences_count', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('word_occurrences_sentence', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Report')),
            ],
        ),
    ]
